version: '3'

services:
    mongo:
      image: mongo:latest
      environment:
          MONGO_INITDB_ROOT_USERNAME : root
          MONGO_INITDB_ROOT_PASSWORD : example
          MONGO_INITDB_DATABASE : scraper
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
      network_mode: "host"

    scrap:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: scraper
      network_mode: "host"

volumes:
  data:
    driver: local
